### PR TITLE
Patriotic Effect AR Filter 

### PR DESCRIPTION
**Pull request by Shreyg-27**
I have added the link of the patriotic effect #3 along with a description

### CODE REVIEW

**Comment by Parul-Mann** [comment]
File name to be descriptive of your contribution, please change it.

**Comment by Shreyg-27** [comment]
I have made the changes required.

**Comment by Parul-Mann** [comment]
Please rename your file from "README.md" to "PatrioticEffect.md" or something similar.

**Comment by Shreyg-27** [comment]
> Please rename your file from "README.md" to "PatrioticEffect.md" or something similar.

I have made the changes

**Pull request merged**
